version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dat
      POSTGRES_PASSWORD: dat
      POSTGRES_DB: bookingService
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:   # volume để data không bị mất khi xoá container

networks:
  backend:
    driver: bridge
